version: '3'
services:
  app:
    build: .
    ports:
      - 4000:4000
    environment:
      - DATABASE_URL=mongodb+srv://weslloll8:jyLdsvUCNJreKeRe@cluster0.ixmag.mongodb.net/skins?retryWrites=true&w=majority&appName=Cluster0